config/routes.rb
Rails.application.routes.draw do
  get 'posts/index'
  get 'posts/new'
  post '/posts/new', to: 'posts#create'
  root "posts#index"
  get    '/signin',   to: 'sessions#new'
  post   '/signin',   to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'
  resources :sessions
  resources :posts, only: [:new, :create, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: {maximum: 20}
  validates :content, presence: true, length: {maximum: 140}
end

app/models/user.rb
class User < ApplicationRecord
 before_create :remember_token  
 has_many :posts 
 has_secure_password

 # Returns a random token.
 def User.new_token
    SecureRandom.urlsafe_base64
  end


 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  attr_accessor :current_user
  

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include SessionsHelper
  before_action :signed_in_user, only: [:new,:create]
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "Post created"
      redirect_to root_url
    else
      render :new
    end
  end


  def signed_in_user
    unless signed_in?
      flash[:danger] = "Please log in"
      redirect_to signin_url
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper

  def new
  end

  def create
   @user = User.find_by(email: params[:session][:email].downcase)
  
   if @user && @user.authenticate(params[:session][:password])
    sign_in(@user)
    flash[:success] = "Signed In Successfully"
    redirect_to posts_index_path
   else 
    render :new
   end

  end

  def destroy
    sign_out if signed_in?
    flash[:success] = "Signed Out Successfully"
    redirect_to root_url
  end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  
# Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

#  Signs in a user
  def sign_in(user)
    session[:user_id] = user.id
  end

   # Remembers a user in a persistent session.
   def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns true if User is signed in

  def signed_in?
    !current_user.nil?
  end

  # Signs out a signed inuser
def sign_out
  session.delete(:user_id)
  @current_user = nil
end
  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(:remember, cookies[:remember_token])
        sign_in user
        @current_user = user
      end
    end
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    
  </small>
  <nav>
    <ul>
      <li><%= link_to "David",   '#' %></li>
      <li><%= link_to "Chibuzor", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "MEMBERS ONLY", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if signed_in? %>
          <li><%= link_to "Sign Out", signout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign In", signin_path %></li>
        <% end %>
        <li><%= link_to "Create Post", new_post_path %></li>
        <li><%= link_to "ALL Posts", root_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render './layouts/header'%>
    <div class="container">
       <% if signed_in? %>Welcome: <%= current_user.name %>
       <% end %>
       <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
             <% end %>
    <%= yield %>
    <!-- <%= debug(params) if Rails.env.development? %> -->
    </div>
    <%= render './layouts/footer'%>
  </body>
</html>

app/views/posts/index.html.erb
<% provide(:title, "Posts") %>
<h1>Posts</h1>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
 
    <% @posts.each do |post| %>
     <div class="inner-posts">
    <% if signed_in? %>
        <p class="author">
      <%= post.user.name %>
      </p>
    <% else %>
    <p class="author">
        Sign In to see the author
        </p>
    <% end %>
     <p class="title">
      <%= post.title %>
      </p>

      <p class="content">
      <%= post.content %> 
      </p>
    </div>
    <% end %>
    
  </div>
</div>

app/views/posts/new.html.erb
<% provide(:title, "Create Post") %>
<h1>Create Post</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:post) do |f| %>
      <% if @post.errors.any? %>
     <div id="error_explanation">
     <h2><%= pluralize(@post.errors.count, "error") %> prohibited this Post from being saved:</h2>


    <ul>
     <% @post.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
     <% end %>
     </ul>
   </div>

<% end %>

      <%= f.label :title %>: 
      <%= f.text_field :title, class: 'form-control' %>


      <%= f.label :content %>: 
      <%= f.text_area :content, class: 'form-control'%>
      <%= f.submit "Submit Post", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>